#!/bin/bash
#
# Watchdog monitor for Claude daemon
# Checks health and auto-restarts if needed
# Alerts to inbox on repeated failures (3+ in 1 hour)
#

set -euo pipefail

DAEMON_ROOT="${HOME}/.claude/daemon"
STATE_FILE="${DAEMON_ROOT}/.watchdog-state.json"
INBOX_DIR="${DAEMON_ROOT}/inbox/human/unread"
LOG_FILE="${DAEMON_ROOT}/logs/watchdog.log"

TMUX_SESSION="claude-daemon"
FAILURE_THRESHOLD=3
FAILURE_WINDOW=3600  # 1 hour in seconds

# Initialize state file if it doesn't exist
if [ ! -f "$STATE_FILE" ]; then
    echo '{"failures": [], "last_alert": null, "restarts": 0}' > "$STATE_FILE"
fi

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

check_daemon_health() {
    # Check both systemd service and tmux session
    local systemd_running=false
    local tmux_running=false

    if systemctl --user is-active --quiet claude-daemon.service 2>/dev/null; then
        systemd_running=true
    fi

    if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
        tmux_running=true
    fi

    # Either should be running (systemd OR tmux OR both)
    if [ "$systemd_running" = true ] || [ "$tmux_running" = true ]; then
        return 0  # healthy
    else
        log "HEALTH CHECK FAILED: systemd=$systemd_running, tmux=$tmux_running"
        return 1  # unhealthy
    fi
}

restart_daemon() {
    log "Attempting to restart daemon..."

    # Try systemd restart first
    if systemctl --user restart claude-daemon.service 2>/dev/null; then
        log "Daemon restarted via systemd"

        # Update restart count
        local restarts=$(jq -r '.restarts' "$STATE_FILE")
        jq --arg count "$((restarts + 1))" '.restarts = ($count | tonumber)' "$STATE_FILE" > "${STATE_FILE}.tmp"
        mv "${STATE_FILE}.tmp" "$STATE_FILE"

        return 0
    else
        log "ERROR: Failed to restart daemon via systemd"
        return 1
    fi
}

record_failure() {
    local now=$(date +%s)

    # Read current failures
    local failures=$(jq -r '.failures | join(" ")' "$STATE_FILE")

    # Add new failure
    failures="$failures $now"

    # Remove failures older than window
    local cutoff=$((now - FAILURE_WINDOW))
    local recent_failures=()
    for timestamp in $failures; do
        if [ "$timestamp" -ge "$cutoff" ]; then
            recent_failures+=("$timestamp")
        fi
    done

    # Update state file
    local failures_json=$(printf '%s\n' "${recent_failures[@]}" | jq -R . | jq -s .)
    jq --argjson failures "$failures_json" '.failures = $failures' "$STATE_FILE" > "${STATE_FILE}.tmp"
    mv "${STATE_FILE}.tmp" "$STATE_FILE"

    # Return count of recent failures
    echo "${#recent_failures[@]}"
}

send_inbox_alert() {
    local failure_count="$1"
    local restarts=$(jq -r '.restarts' "$STATE_FILE")

    local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    local message_id="watchdog-alert-$(date +%Y%m%d-%H%M%S)"
    local filepath="${INBOX_DIR}/${message_id}.md"

    cat > "$filepath" <<EOF
---
from: watchdog
to: human
timestamp: $timestamp
priority: high
tags: ["alert", "auto-recovery", "daemon-health"]
reply_to: null
message_id: $message_id
---

# ⚠️ Daemon Auto-Recovery Alert

The watchdog detected repeated daemon failures and has been auto-restarting it.

## Status

- **Failures in last hour**: $failure_count
- **Total restarts (all time)**: $restarts
- **Alert threshold**: $FAILURE_THRESHOLD failures/hour
- **Current time**: $(date +'%Y-%m-%d %H:%M:%S %Z')

## What Happened

The daemon has failed $failure_count times in the last hour. The watchdog has automatically restarted it each time, but this pattern indicates a potential issue that may need human attention.

## Possible Causes

1. **Crash in Claude CLI**: The claude command may be encountering errors
2. **Resource constraints**: Out of memory or CPU limits
3. **Configuration issue**: Settings may need adjustment
4. **Network problems**: API connectivity issues

## Recommended Actions

1. Check systemd logs: \`journalctl --user -u claude-daemon -n 100\`
2. Check activity log: \`tail -100 ~/.claude/daemon/logs/activity.log\`
3. Check system resources: \`free -h\` and \`top\`
4. Review recent tasks in queue.md
5. Check for error patterns in persona-voice.log

## Auto-Recovery Status

✅ Watchdog is actively monitoring and will continue auto-restarting
✅ systemd is configured for automatic restart on failure
✅ User lingering ensures survival after logout

The daemon should be running now. Use \`~/.claude/daemon/claude-daemon-status.sh\` to verify.

---

**Generated by**: claude-daemon-watchdog
**Next check**: 5 minutes
EOF

    log "ALERT: Sent inbox message to human ($failure_count failures)"

    # Update last alert time
    jq --arg time "$timestamp" '.last_alert = $time' "$STATE_FILE" > "${STATE_FILE}.tmp"
    mv "${STATE_FILE}.tmp" "$STATE_FILE"
}

should_send_alert() {
    local failure_count="$1"

    # Check if we've hit the threshold
    if [ "$failure_count" -lt "$FAILURE_THRESHOLD" ]; then
        return 1  # don't alert yet
    fi

    # Check if we've already alerted recently (within last hour)
    local last_alert=$(jq -r '.last_alert' "$STATE_FILE")
    if [ "$last_alert" != "null" ]; then
        local last_alert_epoch=$(date -d "$last_alert" +%s 2>/dev/null || echo 0)
        local now=$(date +%s)
        local time_since_alert=$((now - last_alert_epoch))

        if [ "$time_since_alert" -lt "$FAILURE_WINDOW" ]; then
            return 1  # already alerted recently
        fi
    fi

    return 0  # should alert
}

# Main watchdog logic
main() {
    log "Watchdog check starting..."

    if check_daemon_health; then
        log "Daemon is healthy"
        exit 0
    fi

    log "Daemon is unhealthy - initiating restart"

    # Record failure
    failure_count=$(record_failure)
    log "Recorded failure (count in last hour: $failure_count)"

    # Restart daemon
    if restart_daemon; then
        log "Restart successful"

        # Check if we should alert
        if should_send_alert "$failure_count"; then
            send_inbox_alert "$failure_count"
        else
            log "No alert needed ($failure_count < $FAILURE_THRESHOLD or recently alerted)"
        fi

        exit 0
    else
        log "ERROR: Restart failed"

        # Always alert on restart failure
        send_inbox_alert "$failure_count"
        exit 1
    fi
}

main
